---
- name: Configure multiple VLANs
  hosts: cisco
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Create VLANs 30 and 40
      ios_config:
        lines:
          - vlan 30
          - name IT
          - vlan 40
          - name HR